//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probaodinadcat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гость.
    /// </summary>
    // *** Start programmer edit section *** (Гость CustomAttributes)

    // *** End programmer edit section *** (Гость CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостьE", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "ДанныеПаспорта as \'Данные паспорта\'",
            "Телефон as \'Телефон\'",
            "Карта as \'Карта\'",
            "Карта.КодКарты as \'Карта\'"}, Hidden=new string[] {
            "Карта.КодКарты"})]
    [MasterViewDefineAttribute("ГостьE", "Карта", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [View("ГостьL", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "ДанныеПаспорта as \'Данные паспорта\'",
            "Телефон as \'Телефон\'",
            "Карта.КодКарты as \'Карта\'"})]
    public class Гость : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private System.DateTime fДатаРождения;
        
        private int fДанныеПаспорта;
        
        private int fТелефон;
        
        private IIS.Probaodinadcat.Карта fКарта;
        
        // *** Start programmer edit section *** (Гость CustomMembers)

        // *** End programmer edit section *** (Гость CustomMembers)

        
        /// <summary>
        /// ДанныеПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Гость.ДанныеПаспорта CustomAttributes)

        // *** End programmer edit section *** (Гость.ДанныеПаспорта CustomAttributes)
        public virtual int ДанныеПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Get start)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Get start)
                int result = this.fДанныеПаспорта;
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Get end)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Set start)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Set start)
                this.fДанныеПаспорта = value;
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Set end)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Гость.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Гость.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Гость.ДатаРождения Get start)

                // *** End programmer edit section *** (Гость.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Гость.ДатаРождения Get end)

                // *** End programmer edit section *** (Гость.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.ДатаРождения Set start)

                // *** End programmer edit section *** (Гость.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Гость.ДатаРождения Set end)

                // *** End programmer edit section *** (Гость.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Телефон CustomAttributes)

        // *** End programmer edit section *** (Гость.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Телефон Get start)

                // *** End programmer edit section *** (Гость.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Гость.Телефон Get end)

                // *** End programmer edit section *** (Гость.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Телефон Set start)

                // *** End programmer edit section *** (Гость.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Гость.Телефон Set end)

                // *** End programmer edit section *** (Гость.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Гость.ФИО CustomAttributes)

        // *** End programmer edit section *** (Гость.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Гость.ФИО Get start)

                // *** End programmer edit section *** (Гость.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Гость.ФИО Get end)

                // *** End programmer edit section *** (Гость.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.ФИО Set start)

                // *** End programmer edit section *** (Гость.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Гость.ФИО Set end)

                // *** End programmer edit section *** (Гость.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Гость.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Карта CustomAttributes)

        // *** End programmer edit section *** (Гость.Карта CustomAttributes)
        [PropertyStorage(new string[] {
                "Карта"})]
        [NotNull()]
        public virtual IIS.Probaodinadcat.Карта Карта
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Карта Get start)

                // *** End programmer edit section *** (Гость.Карта Get start)
                IIS.Probaodinadcat.Карта result = this.fКарта;
                // *** Start programmer edit section *** (Гость.Карта Get end)

                // *** End programmer edit section *** (Гость.Карта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Карта Set start)

                // *** End programmer edit section *** (Гость.Карта Set start)
                this.fКарта = value;
                // *** Start programmer edit section *** (Гость.Карта Set end)

                // *** End programmer edit section *** (Гость.Карта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостьE", typeof(IIS.Probaodinadcat.Гость));
                }
            }
            
            /// <summary>
            /// "ГостьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостьL", typeof(IIS.Probaodinadcat.Гость));
                }
            }
        }
    }
}
